#!/bin/sh
#
#  TODO:
#  - show planned operations and wait for [y/N] confirmation unless -y given
#  - -o output option -- choose a destination dir, default=$pwd
#  - -r raw option -- don't create new folder for each archive
#  - auto detection of path/to/dir in arguments as output destination

esc='\033'
reset="${esc}[0m"
red="${esc}[31m"
green="${esc}[32m"
blue="${esc}[34m"

OUTPUT=$PWD

USAGE="\nUsage:\n
  ex file.tar.gz file2.rar 'file 3.tar.xz' ...\n
  Pass to ex as many"
SUPPORTED="\n
Supported programs and formats:\n\n
  tar            > .tar .bz2 .tar.gz .tbz2 .tbgz .tar.xz .tar.lzma\n
  unrar          > .rar\n
  gunzip         > .gz\n
  unzip          > .zip\n
  uncompress     > .tar.bz2\n
  7z             > .7z\n
  lzma || unlzma > .lzma\n
  lz4            > .lz4\n"
HELP="\nExtractor (ex)\n\n
  Extract one or many archives in a single command\n
  For the lazy ones who don't want to learn all the cli compression programs\n
  Supports different formats in a single command\n
  \n
  Options:\n
  -h Display this page\n
  -o Use last argument as path to output directory (default=\$PWD)\n
  \n
  Examples:\n
  ex files.tar.gz #### extract files.tar.gz into new directory \$PWD/files\n
  ex -o files.tar.gz /tmp #### extract to a new directory in /tmp\n
  ex -r files.tar.gz files2.zip -o ~/Directory #### extract all archives content in ~/Directory/ (no new directories)\n
  $SUPPORTED"

if [ "$#" -eq 0 ] ; then
  echo $USAGE
  echo "ex -h to see more"
  exit 1
fi

while getopts "ho" OPTION; do
  case $OPTION in
    h) echo $HELP; exit 1 ;;
    o) OUTPUT=$NF
  esac
done

for arg in "$@" ; do
  if [ -f $arg ] ; then
    echo "extracting '$arg'..."
    case $arg in
      *.tar.bz2)   tar xjf $arg $OUTPUT ;;
      *.tar.gz)    tar xzf $arg $OUTPUT ;;
      *.bz2)       bunzip2 $arg $OUTPUT ;;
      *.rar)       unrar x $arg $OUTPUT ;;
      *.gz)        gunzip  $arg $OUTPUT ;;
      *.tar)       tar xf  $arg $OUTPUT ;;
      *.tbz2)      tar xjf $arg $OUTPUT ;;
      *.tbgz)      tar xzf $arg $OUTPUT ;;
      *.zip)       unzip   $arg $OUTPUT ;;
      *.tar.bz2)   uncompress $arg $OUTPUT ;;
      *.7z)        7z x $arg $OUTPUT ;;
      *.tar.xz)    tar xf $arg $OUTPUT ;;
      *.tar.lzma)  tar --lzma -xvf $arg $OUTPUT ;;
      *.lzma)      lzma -d $arg || unlzma $arg $OUTPUT ;;
      *.lz4)       lz4 -d $arg $OUTPUT ;;
      *)           echo "$red ex cannot extract '$arg'$reset" ;;
    esac
  else
    echo "$red$arg is not a valid file!$reset"
    echo $SUPPORTED
  fi
done
